# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: http://people.rit.edu/~lja5234
:url: http://people.rit.edu/~lja5234
#:site_name: http://localhost:5000
:copyright: 2013
:analytics_code: UA-00000000-0
