title: RIT Rides

# github: nothin here...

body: |
   RIT rides is a side-project I started on a train
   ride home. It (eventually) will allow people with cars
   to be matched up to people without cars so they can
   get rides to the grocery store, or the mall.
   
   I took this project as a chance to get reaquanted with
   <a href="http://django.org">django</a>, an awesome 
   pseudo-MVC framework that uses python. 
