title: Ethereal Commerce

github: https://github.com/leeavital/ethereal-commerce

body: |
   Ethereal Commerce is the first large scale PHP framnework I 
   every developed. It's a framework for creating themable ecommerce system
   with a admin dashboard. It's based heavily on (older versions) of 
   wordpress &mdash; in other words, there are global functions everywhere!

   When I first got into PHP I was really into wordpress, so I wanted to
   build a themable system just like wordpress. 

   Take a look at a basic template file:

   <pre>
   &lt;?php get_header(); ?&gt;

   &lt;?php while ($epc_query-&gt;hasNext()): ?&gt;


   &lt;a href="&lt;?= p_href(); ?&gt;"&gt;
   &lt;?php p_title(); ?&gt; &lt;br /&gt;
   &lt;/a&gt;
   &lt;?php p_description(); ?&gt; &lt;br /&gt;
   &lt;?php p_controls(); ?&gt; &lt;br /&gt;

   &lt;?php p_category(); ?&gt;

   &lt;br /&gt;
   &lt;br /&gt;
   &lt;br /&gt;

   &lt;?php $epc_query-&gt;next(); ?&gt;
   &lt;?php endwhile ?&gt;

   &lt;?php get_footer(); ?&gt;
   </pre>



