title:
  SNAP

github: http://github.com/leeavital/SNAP

body: |
   SNAP stands for 
   <b>s</b>hared <b>n</b>amespace <a>a</a>pplication 
   <a>p</a>rogramming. It's a small PHP utility I wrote that allows
   you to write functions in PHP and wrap them up into javascript modules.
   This allows you to essentially call server side code from the browser
   without fussing with AJAX.

   There's still plently of work for this project. PHP runtime errors 
   transition somewhat gracefully to javascript, but parse exceptions
   do not &mdash; in other words, a syntax error will throw a major 
   wrench in the works.
   


   Let's look at some PHP!

      <pre>
      
      // file name: bar.php

      function getUserInfo($username){
         // do some server side operations
      }
      
      </pre> 
      
      
      <pre>
      
      // file name: foo.js.php

      // create a new module.
      $module = new SNAPModule("SNAP");      
      

      // register the function bar() in bar.php as foo.
      $module->registerFunction("foo", "bar", "bar.php");      
      

      // write JS to the page.
      SNAPTrigger($module);     
      
      </pre>
     

   Now let's look at some HTML!
      
      <pre>
      
      // file name: index.html

      &lt;script type="text/javascript" src="foo.js.php"&gt;&lt;script&gt;
      &lt;script type="text/javascript"&gt;
        
        // this function was written in PHP.
        var something = SNAP.foo("some-user-name");  
     
      &lt;script&gt;

      </pre>

