title: About Me


body: |
  Hi, my name is  **Lee Avital** and I'm a fourth year computer science
  student at the [Rochester Institute of Technology](http://rit.edu "RIT")

  I recently finished an internship at [Drawbridge](http://drawbrid.ge) as
  a platform intern and will soon be starting an internship at [Twitter](http://twitter.com "Twitter")


  I've done a lot of work in **web development** &mdash; writing
  large javascript applications with backends in Scala, PHP, and
  ASP Classic.

  Some of my experience:

  - I've worked at [Massdrop](http://massdrop.com "Massdrop") as an engineer. Massdrop is
   a platform that allows buyers to leverage their numbers and get better
   prices on the products they want.
   
  - I've worked as a web developer at the [National Technical Institute for the Deaf](http://ntid.rit.edu "NTID")
  working on web-based  tools to enhance the classroom experience for both hearing and 
  non-hearing students.



  I'm very interested in programming languages. Right now, my language of choice
  is [Scala](https://en.wikipedia.org/wiki/Scala_(programming_language "Scala"), a
  strongly typed, functional programming language that runs on the JVM
