body:  
  <p>Hi, my name is Lee Avital and I'm a second year computer
  science at the <a href="http://rit.edu" title="Rochester Institute 
  of Technology">Rochester Institute of Technology</a>. My primary interests
  are in language theory/design and web development. </p>
  
  <p>I currently work at the <a href="http://ntid.rit.edu" title="NTID">National
  Technical Institute for the Deaf</a> where I write and maintain educational web
  based software. </p> 
  

  

title:
  Lee Avital
