title: This Website

github: https://github.com/leeavital/personal-site

date: 1/5/2013

body: |
   This site was written using the delightful 
   <a href="http://tinytree.info">bonsai static site generator</a>
   by <a href="http://twitter.com/benschwarz">Ben Shwarz</a>. A great
   tool build in ruby that lets me write my content in YAML files
   and my templates in liquid.


   It also autocompiles SASS automatically so I implemented some
   css based responsive design.  Go ahead and resize that page!


