# Site settings
title: LeeAvital.com
email: leeavital@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leeavital.com" # the base hostname & protocol for your site
twitter_username: leeavital
github_username:  leeavital

# Build settings
markdown: kramdown
